server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 272004
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc.time_zone: UTC

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

project:
  images : images/

base:
  url: http://localhost:8080

app:
  jwt:
    secret: mySecretKey12345678901234567890123456789012345678901234567890
    expiration: 86400000

cors:
  allowed-origins: "http://localhost,http://frontend"

logging:
  level:
    com.example.usermanagement: INFO
    org.springframework.security: DEBUG
